In [8]:
import pandas as pd
import json

data = {
    "identificacion": {
        "nombres_completos": "CHILLOGALLI MOROCHO DALYSS PAOLA",
        "cedula": "1150037024",
        "fecha_nacimiento": "2007-12-02",
        "lugar_nacimiento": "AZUAY / CUENCA / HUAYNACAPAC",
        "nacionalidad": "ECUATORIANA",
        "sexo": "MUJER",
        "estado_civil": "SOLTERO",
        "instruccion_basica": "ESTUDIANTE",
        "padre": "CHILLOGALLI DOMINGUEZ CESAR AUGUSTO",
        "madre": "MOROCHO CABRERA DIANA CECIBEL"
    },
    "seguridad_social": {
        "iess": "Persona no afiliada al IESS"
    },
    "historial_vacunacion": {
        "vacunas": [
            {
                "nombre": "BNT162b2 PFIZER",
                "dosis": 1,
                "fecha": "2021-09-22"
            }
        ]
    },
    "informacion_academica": {
        "titulo": "Bachiller en Ciencias",
        "institucion": "Unidad Educativa Fiscomisional San José De Calasanz",
        "fecha_grado": "2025-06-03"
    },
    "informacion_adicional": {
        "direccion_domicilio": "LUIS FERNANDO ORDOÑEZ SUCRE CE, Parroquia SARAGURO, Cantón SARAGURO, Provincia de LOJA",
        "lugar_votacion": "UE Saraguro, Loja/Saraguro"
    },
    "situacion_legal": {
        "supa_pensiones_alimenticias": "NO registra información",
        "impedimentos_cargos_publicos": "NO",
        "prohibicion_salida_pais": "NO"
    },
    "datos_agregados": {
        "Edad_Calculada": "17 años, 10 meses, 24 días (calculado al 2025-10-26)",
        "Hoja_de_Rutina": {
            "dia_jueves_18_de_noviembre": "3:50 PM: Baja de el coliseo divirtiéndose en básquet"
        }
    }
}

# Flatten the nested dictionary
def flatten_dict(d, parent_key='', sep='_'):
    items = []
    for k, v in d.items():
        new_key = parent_key + sep + k if parent_key else k
        if isinstance(v, dict):
            items.extend(flatten_dict(v, new_key, sep=sep).items())
        elif isinstance(v, list):
            for i, item in enumerate(v):
                 if isinstance(item, dict):
                     items.extend(flatten_dict(item, new_key + sep + str(i), sep=sep).items())
                 else:
                     items.append((new_key + sep + str(i), item))
        else:
            items.append((new_key, v))
    return dict(items)

flattened_data = flatten_dict(data)

# Create a pandas DataFrame from flattened data
df = pd.DataFrame([flattened_data])

# Get the flattened data from the DataFrame
flattened_data_row = df.iloc[0].to_dict()

# Create a list of dictionaries with 'Seccion' and 'Impacto'
reformatted_data = []
for key, value in flattened_data_row.items():
    # Split the key to get the main section
    section = key.split('_')[0] if '_' in key else key
    reformatted_data.append({'Seccion': section, 'Impacto': value})

# Create a new DataFrame from the reformatted data
df_reformatted = pd.DataFrame(reformatted_data)

# Add new rows for 'altura' and 'peso'
new_data = [
    {'Seccion': 'datos_agregados', 'Impacto': 'altura: 1.60m'},
    {'Seccion': 'datos_agregados', 'Impacto': 'peso: 65kg / x libras'}
]

df_reformatted = pd.concat([df_reformatted, pd.DataFrame(new_data)], ignore_index=True)


# Display the updated DataFrame
display(df_reformatted)

# Save the reformatted DataFrame to a CSV file
df_reformatted.to_csv('datos_reformatados.csv', index=False)

print("\nDataFrame guardado en 'datos_reformatados.csv'")

# Example of modifying a value (let's change the 'Estado Civil')
# Find the index of the row where 'Seccion' is 'identificacion' and 'Impacto' contains 'SOLTERO'
index_to_modify = df_reformatted[(df_reformatted['Seccion'] == 'identificacion') & (df_reformatted['Impacto'].str.contains('SOLTERO'))].index[0]

# Modify the 'Impacto' for that row
df_reformatted.loc[index_to_modify, 'Impacto'] = 'CASADO'

print("\nDataFrame después de la modificación:")
display(df_reformatted)

# Example of printing a specific value (let's print the modified 'Estado Civil')
modified_estado_civil = df_reformatted.loc[index_to_modify, 'Impacto']
print(f"\nEl nuevo estado civil es: {modified_estado_civil}")

            Seccion                                            Impacto
0    identificacion                   CHILLOGALLI MOROCHO DALYSS PAOLA
1    identificacion                                         1150037024
2    identificacion                                         2007-12-02
3    identificacion                       AZUAY / CUENCA / HUAYNACAPAC
4    identificacion                                        ECUATORIANA
5    identificacion                                              MUJER
6    identificacion                                            SOLTERO
7    identificacion                                         ESTUDIANTE
8    identificacion                CHILLOGALLI DOMINGUEZ CESAR AUGUSTO
9    identificacion                      MOROCHO CABRERA DIANA CECIBEL
10        seguridad                        Persona no afiliada al IESS
11        historial                                    BNT162b2 PFIZER
12        historial                                                  1
13        historial                                         2021-09-22
14      informacion                              Bachiller en Ciencias
15      informacion  Unidad Educativa Fiscomisional San José De Cal...
16      informacion                                         2025-06-03
17      informacion  LUIS FERNANDO ORDOÑEZ SUCRE CE, Parroquia SARA...
18      informacion                         UE Saraguro, Loja/Saraguro
19        situacion                            NO registra información
20        situacion                                                 NO
21        situacion                                                 NO
22            datos  17 años, 10 meses, 24 días (calculado al 2025-...
23            datos  3:50 PM: Baja de el coliseo divirtiéndose en b...
24  datos_agregados                                      altura: 1.60m
25  datos_agregados                              peso: 65kg / x libras

DataFrame guardado en 'datos_reformatados.csv'

DataFrame después de la modificación:

            Seccion                                            Impacto
0    identificacion                   CHILLOGALLI MOROCHO DALYSS PAOLA
1    identificacion                                         1150037024
2    identificacion                                         2007-12-02
3    identificacion                       AZUAY / CUENCA / HUAYNACAPAC
4    identificacion                                        ECUATORIANA
5    identificacion                                              MUJER
6    identificacion                                             CASADO
7    identificacion                                         ESTUDIANTE
8    identificacion                CHILLOGALLI DOMINGUEZ CESAR AUGUSTO
9    identificacion                      MOROCHO CABRERA DIANA CECIBEL
10        seguridad                        Persona no afiliada al IESS
11        historial                                    BNT162b2 PFIZER
12        historial                                                  1
13        historial                                         2021-09-22
14      informacion                              Bachiller en Ciencias
15      informacion  Unidad Educativa Fiscomisional San José De Cal...
16      informacion                                         2025-06-03
17      informacion  LUIS FERNANDO ORDOÑEZ SUCRE CE, Parroquia SARA...
18      informacion                         UE Saraguro, Loja/Saraguro
19        situacion                            NO registra información
20        situacion                                                 NO
21        situacion                                                 NO
22            datos  17 años, 10 meses, 24 días (calculado al 2025-...
23            datos  3:50 PM: Baja de el coliseo divirtiéndose en b...
24  datos_agregados                                      altura: 1.60m
25  datos_agregados                              peso: 65kg / x libras

El nuevo estado civil es: CASADO